# Generated by Django 3.2.18 on 2023-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUAP', models.CharField(max_length=7, null=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
