# Generated by Django 3.2.18 on 2023-03-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aluno',
            new_name='psicologa',
        ),
    ]
