# Generated by Django 4.1.7 on 2023-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologa', '0002_rename_aluno_psicologa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologa',
            name='id',
        ),
        migrations.AlterField(
            model_name='psicologa',
            name='SUAP',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
