# Generated by Django 4.1.1 on 2023-03-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0004_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='datadenascimento',
            field=models.DateField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
