# Generated by Django 4.1.7 on 2023-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0005_aluno_datadenascimento_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
