# Generated by Django 4.1.7 on 2023-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0006_remove_aluno_id_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
