# Generated by Django 4.1.7 on 2023-04-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Indicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='idresp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indicacao.responsavel'),
        ),
    ]
