# Generated by Django 4.1.7 on 2023-04-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aluno', '0006_remove_aluno_id_alter_aluno_matricula'),
        ('Psicologa', '0003_remove_psicologa_id_alter_psicologa_suap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaatendimento', models.DateField(max_length=12, null=True)),
                ('observacoes', models.CharField(max_length=300)),
                ('SUAPPsicologa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Psicologa.psicologa')),
                ('matriculaaluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluno.aluno')),
            ],
        ),
    ]
