# Generated by Django 4.1.7 on 2023-04-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='id',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='diaatendimento',
            field=models.DateField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='motivo',
            fields=[
                ('IDmotivo', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristicaspessoaisracionais', models.CharField(max_length=20, null=True)),
                ('outros', models.CharField(max_length=40)),
                ('motivogeral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.atendimento')),
            ],
        ),
    ]
