# Generated by Django 4.1.7 on 2023-04-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0009_alter_aluno_matricula'),
        ('Psicologa', '0004_alter_psicologa_suap'),
        ('Atendimento', '0003_encontro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='SUAPPsicologa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Psicologa.psicologa'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='matriculaaluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aluno.aluno'),
        ),
    ]
