# Generated by Django 4.1.7 on 2023-04-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Indicacao', '0002_indicacao_idresp'),
        ('Atendimento', '0004_alter_atendimento_suappsicologa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='indicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indicacao.indicacao'),
        ),
    ]
